import {
  Activity,
  Archive,
  Banknote,
  Bitcoin,
  Brain,
  GraduationCap,
  KeyRound,
  Landmark,
  LayoutGrid,
  Library,
  LineChart,
  Mail,
  MapPin,
  Mic,
  RefreshCw,
  Sliders,
} from 'lucide-react';

export const SETTINGS_SECTIONS = [
  {
    id: 'general',
    label: 'General',
    description: 'Display, privacy and entities',
    icon: Sliders,
    keywords: 'numbers blur name color icon',
  },
  {
    id: 'keys',
    label: 'AI & Chat',
    description: 'Providers, API keys and models',
    icon: KeyRound,
    keywords: 'anthropic openai claude codex',
  },
  {
    id: 'brain',
    label: 'Brain',
    description: 'Your assistant’s long-term memory',
    icon: Brain,
    keywords: 'markdown notes preferences',
  },
  {
    id: 'skills',
    label: 'Skills',
    description: 'Reusable instructions for chat',
    icon: GraduationCap,
    keywords: 'markdown files workflows prompts',
  },
  {
    id: 'email',
    label: 'Email',
    description: 'Delivery settings and sent mail',
    icon: Mail,
    keywords: 'smtp resend reports',
  },
  {
    id: 'maps',
    label: 'Location',
    description: 'Maps, weather and calendar',
    icon: MapPin,
    keywords: 'geoapify birthdays forecast',
  },
  {
    id: 'voice',
    label: 'Voice',
    description: 'Speech and audio preferences',
    icon: Mic,
    keywords: 'microphone transcription',
  },
  {
    id: 'sync',
    label: 'Sync & Schedules',
    description: 'Dropbox and automatic updates',
    icon: RefreshCw,
    keywords: 'backup password snapshot news',
  },
  {
    id: 'sources',
    label: 'External Sources',
    description: 'Connected repositories',
    icon: Library,
    keywords: 'git files markdown sync',
  },
  {
    id: 'status',
    label: 'Status',
    description: 'System health and logs',
    icon: Activity,
    keywords: 'errors tasks history',
  },
  {
    id: 'jobs',
    label: 'Jobs',
    description: 'Scheduled and custom tasks',
    icon: Activity,
    keywords: 'automation scripts run',
  },
  {
    id: 'banking',
    label: 'Banking',
    description: 'Bank and broker connections',
    icon: Banknote,
    keywords: 'simplefin snaptrade accounts',
  },
  {
    id: 'crypto',
    label: 'Crypto',
    description: 'Exchanges, wallets and holdings',
    icon: Bitcoin,
    keywords: 'coinbase kraken etherscan',
  },
  {
    id: 'quant',
    label: 'Quant',
    description: 'Market data and FRED',
    icon: LineChart,
    keywords: 'economics finance key',
  },
  {
    id: 'politics',
    label: 'Politics',
    description: 'Congress data and refreshes',
    icon: Landmark,
    keywords: 'api bills backtest',
  },
  {
    id: 'backup',
    label: 'Backup',
    description: 'Download and restore your data',
    icon: Archive,
    keywords: 'encryption export import',
  },
  {
    id: 'all',
    label: 'All settings',
    description: 'Every section on one page',
    icon: LayoutGrid,
    keywords: '',
  },
] as const;

export function validSettingsSection(value: string | null): string {
  return SETTINGS_SECTIONS.some((section) => section.id === value) ? value! : 'general';
}
